# Dockerfile.dev
FROM node:20.18.1-alpine

# Install expo-cli globally
RUN npm install -g @expo/cli

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY . .

# Expose Expo DevTools and Metro Bundler ports
EXPOSE 8081 19000 19001 19002

# Start Expo development server
CMD ["npm", "start"]
